---

# TODO: remove folder /root/.oh-my-zsh

#- name: install oh-my-zsh (archlinux)
#  kewlfft.aur.aur:
#    name: oh-my-zsh-git
#    state: present
#  when: ansible_distribution == "Archlinux"

- name: remove oh-my-zsh existing install if any
  ansible.builtin.file:
    path: /root/.oh-my-zsh/
    state: absent

- name: Download oh-my-zsh Installer
  get_url:
    url: "{{ oh_my_zsh_url }}"
    dest: /tmp/zsh-installer.sh

- name: Install oh-my-zsh
  script: /tmp/zsh-installer.sh

- name: Install zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: /root/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    depth: 1

- name: Install zsh-completions plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-completions
    dest: /root/.oh-my-zsh/custom/plugins/zsh-completions
    depth: 1

- name: Install zsh-syntax-highlighting plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: /root/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    depth: 1

- name: Install zsh-nvm plugin (nodejs version manager)
  ansible.builtin.git:
    repo: https://github.com/lukechilds/zsh-nvm
    dest: /root/.oh-my-zsh/custom/plugins/zsh-nvm
    depth: 1

- name: Install zsh-z plugin
  ansible.builtin.git:
    repo: https://github.com/agkozak/zsh-z
    dest: /root/.oh-my-zsh/custom/plugins/zsh-z
    depth: 1

- name: set user zshrc
  ansible.builtin.copy:
    src: zshrc
    dest: /root/.zshrc

- name: preload nvm in zsh
  ansible.builtin.command: "zsh -c 'source ~/.zshrc && nvm install node'"

...