---
# tasks file for c2-metasploit

- name: install application
  ansible.builtin.include_tasks: ../../lib-tasks/generic-add-app.yml
  vars:
    name: msfconsole
    package: metasploit
  when: ansible_distribution == "Archlinux"

- name: install application
  ansible.builtin.include_tasks: ../../lib-tasks/generic-add-app.yml
  vars:
    name: msfconsole
    package: metasploit-framework
  when: ansible_distribution == "Kali"
...