---

- name: firefox archlinux
  include_tasks: firefox_archlinux.yml
  when: ansible_distribution == "Archlinux"

- name: install firefox
  ansible.builtin.package:
    name:
      - firefox-esr
    state: present
  when: ansible_distribution == "Kali"


#- name: add history
#  ansible.builtin.include_tasks: ../../lib-tasks/add-history.yml
#  vars:
#    name: firefox

...