---
# tasks file for env-base

- name: install usefull tools (1)
  ansible.builtin.package:
    name:
      - autoconf
      - automake
      - chromium
      - cmake
      - dos2unix
      - gcc # C and C++ compiler
      - git
      - gnupg
      - jq
      - make
    state: present

- name: install usefull tools (2)
  ansible.builtin.package:
    name:
      - nano
      - npm
      - p7zip
      - perl
      - sshpass
      #- telnet
      - tidy
      - time
    state: present

- name: install usefull tools (3)
  ansible.builtin.package:
    name:
      - tree
      - tmux
      - unrar
      - unzip
      - wget
      - zip
      - zsh
    state: present

- name: install usefull tools (arch)
  ansible.builtin.package:
    name:
      - go
      - jdk11-openjdk
      - jre11-openjdk
      - jre11-openjdk-headless
      - jdk17-openjdk
      - jre17-openjdk
      - jre17-openjdk-headless
      - xz
    state: present
  when: ansible_distribution == "Archlinux"

- name: install usefull tools (Kali)
  ansible.builtin.package:
    name:
      - openjdk-17-jre
      - openjdk-17-jdk
      - openjdk-17-jdk-headless
      - xz-utils
    state: present
  when: ansible_distribution == "Kali"

- name: "Change shell to /bin/zsh"
  user:
    name: root
    shell: /bin/zsh

- name: install application
  ansible.builtin.include_tasks: "{{ role_path }}/../../lib-tasks/generic-add-app.yml"
  vars:
    name: "{{ item }}"
    package: "{{ item }}"           # deb or yum or pacman ...
  with_items:
    - curl
    - dnsutils

- name: arsenal
  include_tasks: arsenal.yml

- name: firefox
  include_tasks: firefox.yml

- name: mdcat
  include_tasks: mdcat.yml

- name: ruby
  include_tasks: ruby.yml

- name: rust
  include_tasks: rust.yml
  when: ansible_distribution == "Archlinux"

- name: screen
  include_tasks: screen.yml

- name: tmux
  include_tasks: tmux.yml

- name: vim
  include_tasks: vim.yml

...