---
# tasks file for office-vscode

- name: install application
  ansible.builtin.include_tasks: ../../lib-tasks/generic-add-app.yml
  vars:
    name: visual-studio-code
    aur_package: visual-studio-code-bin

...