---

- name: add history
  ansible.builtin.include_tasks: ../../lib-tasks/add-history.yml
  vars:
    name: "{{ item }}"
  with_items:
    - smb
    - samba

- name: install application
  ansible.builtin.include_tasks: ../../lib-tasks/generic-add-app.yml
  vars:
    name: smbclient
    package: smbclient

...