---
# tasks file for system-base

- name: Distribution name
  debug: var=ansible_distribution
- name: Distribution familly
  debug: var=ansible_os_family

- name: Distribution version
  debug: var=ansible_distribution_version
- name: Distribution release
  debug: var=ansible_distribution_release
- name: Distribution major version
  debug: var=ansible_distribution_major_version

- name: install base packages
  ansible.builtin.package:
    name:
      - binutils
      - fakeroot   # used to build packages from AUR
      - git        # used to build packages from AUR
      - iproute2
      - logrotate
      - man-db
      # - mlocate   # replaced by plocate
      - net-tools
      - openresolv
      - plocate
      - sudo
    state: present

- name: install base packages (arch)
  ansible.builtin.package:
    name:
      - bind  # dnsutils, nslookup, dig
      - iputils
      - jack2
    state: present
  when: ansible_distribution == "Archlinux"

- name: install base packages (debian)
  ansible.builtin.package:
    name:
      - dnsutils # nslookup, dig
      - locales
    state: present
  when: ansible_distribution == "Kali"

- name: Set locale
  include_tasks: sys-locale.yml
  when: ansible_distribution == "Archlinux"

- name: update Archlinux packages
  include_tasks: packages-update-archlinux.yml
  when: ansible_distribution == "Archlinux"

- name: update Debian packages
  include_tasks: packages-update-debian.yml
  when: ansible_distribution == "Kali"

- name: BlackArch
  include_tasks: packages-blackarch.yml
  when: ansible_distribution == "Archlinux"

- name: prepare for AUR building
  include_tasks: packages-AUR.yml
  when: ansible_distribution == "Archlinux"

#- name: paru (archlinux AUR helper)
#  include_tasks: packages-paru.yml
#  when: ansible_distribution == "Archlinux"

- name: install some utilities (archlinux)
  ansible.builtin.package:
    name:
      - pacman-contrib
    state: present
  when: ansible_distribution == "Archlinux"

...